INSERT INTO film (id, name)
VALUES (1, 'Le Seigneur des Anneaux'),
       (2, 'Forrest Gump'),
       (3, 'Pulp Fiction'),
       (4, 'Fight Club'),
       (5, 'Inception'),
       (6, 'Le Parrain'),
       (7, 'Matrix'),
       (8, 'Le Silence des Agneaux'),
       (9, 'Le Bon, la Brute et le Truand'),
       (10, 'Les Évadés'),
       (11, 'Gladiator'),
       (12, 'Le Retour du Roi'),
       (13, 'Le Voyage de Chihiro'),
       (14, 'Interstellar'),
       (16, 'Le Roi Lion'),
       (17, 'The Dark Knight'),
       (18, 'Forrest Gump 2'),
       (19, 'Le Labyrinthe de Pan'),
       (20, 'Les Affranchis'),
       (21, 'Les Cinq Légendes'),
       (22, 'Le Loup de Wall Street'),
       (23, 'Django Unchained'),
       (24, 'Retour vers le Futur'),
       (25, 'La La Land'),
       (26, 'Le Prestige'),
       (27, 'Blade Runner'),
       (28, 'Inglourious Basterds'),
       (29, 'Casino'),
       (30, 'Dunkerque'),
       (31, 'American History X');